spring:
  application:
    name: lzl-ai-agent
  ai:
    dashscope:
      api-key: sk-11d21bc129044becadb43a491cc5f410
      chat:
        options:
          model: qwen-plus

server:
  port: 8080

# knife4j的增强配置，不需要增强可以不配(建议配置一下)
knife4j:
  enable: true    #开启knife4j,无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    swagger-model-name: class list   #重命名SwaggerModel名称,默认